### ISSUE TITLE
Scroll position

### ISSUE THREAD

**Issue by pdrbrnd** [pdrbrnd/whatsinthebox#3]
### Description:
After opening a movie detail, the scroll is not kept in the correct place and we're forced to scroll back up.

**Comment by jca41** [comment]
Are you taking contributors? You like to help on this!

**Comment by pdrbrnd** [comment]
sure! I don't see why not

**Comment by jca41** [comment]
👍  awesome! 
Regarding dev setup, are you able to provide a mock with a few movies so i don't need API access?
Or do you have a test environment?

**Comment by pdrbrnd** [comment]
@jca41 just updated `.env.example` with the graphql endpoint – which is not a secret at all. It's just there for convenience when switching environments.

now you should be able to run the project.

thanks for the help :)

**Comment by jca41** [comment]
@pdrbrnd What node version are you using? Getting a few prettier errors, i'm using 15.8.

**Comment by pdrbrnd** [comment]
@jca41 I'm at 16.2 but I don't think that's the problem.
we had a few updates at significa-style that probably should have been a major bump and I'm not using exact versions in this project.

I'll update the packages.

sorry about that, I wasn't counting on collaboration here 😅

**Comment by jca41** [comment]
using npm fixed it for me 😄  was using yarn initially.
