### ISSUE TITLE
No movies present in the website

### ISSUE THREAD

**Issue by IvoPereira** [pdrbrnd/whatsinthebox#9]
### Description:
The website does not present any movie at all.

I have read somewhere in Reddit a few months ago that someone was able to find movies when they started filtering, but even that does not work.

Looking at the code (src/pages/api/*), it appeared that the import process is a manual step that is done now and then? If so, that probably is the cause of this. Can we work further on making this automatic so the website main purpose isn't disrupted?

**EDIT:** I have just [discovered from another issue](https://github.com/pdrbrnd/whatsinthebox/issues/4#issuecomment-892188984) that the schedule is currently pulled every midnight. Might be something wrong with that process then? I would love to debug it but I am unsure how to replicate it locally.

#### Details:
![image](https://user-images.githubusercontent.com/1396475/132988054-2e382588-0d9c-47cc-9444-d4644229fcc8.png)

---

_Para contexto, este issue foi criado no âmbito do Challenge devPT - https://www.reddit.com/r/devpt/comments/pmeuh5/challenge_devpt_1/._

**Comment by pdrbrnd** [comment]
This shouldn't be happening.
I will try to debug in a few hours and I'll keep you posted.

This project is just the front-end for a graphql API and you shouldn't have to spin up a local backend to work on this. Unfortunately, there's just a single "production" instance and not multiple environments.

**Comment by pdrbrnd** [comment]
@IvoPereira thanks for the heads up.

someone I misconfigured sentry and I got no alerts when my queue started failing more than one week ago 😱 

#11 solved the problem
